<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><groupId>com.uelbosque</groupId><artifactId>tienda-services</artifactId><version>0.0.1-SNAPSHOT</version><packaging>pom</packaging><modules><module>platform-common</module><module>user-service</module><module>customer-service</module><module>supplier-service</module><module>catalog-service</module><module>cart-service</module><module>order-service</module><module>inventory-service</module><module>payment-service</module><module>notification-service</module><module>admin-service</module><module>config-server</module><module>gateway</module></modules></project>
